export const CONTACT_LOADING = "CONTACT_LOADING";
export const CONTACT_SUCCESS = "CONTACT_SUCCESS";
export const CONTACT_ERROR = "CONTACT_ERROR";
export const ENABLE_SUBMIT = "ENABLE_SUBMIT";

export const QUOTE_LOADING = "QUOTE_LOADING";
export const QUOTE_SUCCESS = "QUOTE_SUCCESS";
export const QUOTE_ERROR = "QUOTE_ERROR";